package com.mine.upmsx.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.mine.common.feign.entity.upmsx.SysLog;
import org.apache.ibatis.annotations.Mapper;

/**
 * @description: 【日志表】映射器
 * @author: Generated by jax-li
 * @create: 2020-08-20
 */
@Mapper
public interface SysLogMapper extends BaseMapper<SysLog> {

}
