package com.mine.upmsx.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.mine.upmsx.entity.SysUserBase;
import org.apache.ibatis.annotations.Mapper;

/**
 * @description: 【登录信息表】映射器
 * @author: Generated by Jax-li
 * @create: 2020-08-12
 * @version: v1.0
 */
public interface SysUserBaseMapper extends BaseMapper<SysUserBase> {

}
