server:
  port: 8761

spring:
  application:
    name: @artifactId@
  security:
    user:
      name: eureka
      password: eureka

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false # false表示当前服务注册中心不在其他服务注册中心进行注册。
    fetch-registry: false # false表示当前服务注册中心不获取其他服务注册中心的注册信息。
    # 以上两个配置，只有在当服务注册中心是单点配置时才如此配置，因为单点情况下这两个值必然为false。
    service-url:
      default-zone: http://127.0.0.1:8761/eureka