package com.mine.upmsx.dto;

import com.baomidou.mybatisplus.annotation.TableLogic;
import com.mine.common.core.valid.AddGroup;
import com.mine.common.core.valid.UpdateGroup;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import javax.validation.constraints.Email;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * @description: 【登录信息表】交互层
 * @author: Generated by Jax-li
 * @create: 2020-08-12
 * @version: v1.0
 */
@Data
@ApiModel(value = "【登录信息表】交互层")
public class SysUserBaseDTO {

    @ApiModelProperty(value = "用户Id")
    private Long id;

    @NotBlank(message = "用户名不能为空", groups = {AddGroup.class})
    @Size(min = 6, max = 20, groups = {UpdateGroup.class, AddGroup.class})
    @ApiModelProperty(value = "用户名")
    private String userName;

    @NotBlank(message = "密码不能为空", groups = {AddGroup.class, UpdateGroup.class})
    @Size(min = 6, max = 20, groups = {UpdateGroup.class, AddGroup.class})
    @ApiModelProperty(value = "登录密码")
    private String password;

    @Pattern(regexp = "1[3-9][0-9]\\d{8}", message = "手机号格式不正确")
    @Size(min = 11, max = 11, message = "手机号格式不正确")
    @ApiModelProperty(value = "移动电话号码")
    private String mobile;

    @Email(message = "邮箱格式不正确")
    @ApiModelProperty(value = "邮箱")
    private String email;

    @Pattern(regexp = "\\d{15}|\\d{18}", groups = {UpdateGroup.class, AddGroup.class})
    @ApiModelProperty(value = "身份证号码")
    private String idCard;

    @ApiModelProperty(value = "是否锁定  1 是 0 否")
    private Integer isLocked;

    @ApiModelProperty(value = "是否启用  1 是 0 否 ")
    private Integer isEnabled;

    @ApiModelProperty(value = "最后登录时间")
    private LocalDate lastLoginTime;

    @TableLogic
    @ApiModelProperty(value = "是否删除 1 是 0 否 ")
    private Integer isDeleted;

    @ApiModelProperty(value = "创建用户Id")
    private Long createUserId;

    @ApiModelProperty(value = "创建用户名称")
    private String createUserName;

    @ApiModelProperty(value = "创建时间")
    private LocalDateTime createTime;

    @ApiModelProperty(value = "修改用户Id")
    private Long updateUserId;

    @ApiModelProperty(value = "更新用户名称")
    private String updateUserName;

    @ApiModelProperty(value = "更新时间")
    private LocalDateTime updateTime;

}