package com.mine.upmsx.vo;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.mine.upmsx.dto.SysLogDTO;
import io.swagger.annotations.ApiModel;
import lombok.Data;

/**
 * @description: 【日志表】响应层
 * @author: Generated by jax-li
 * @create: 2020-08-20
 */
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@ApiModel(value = "【日志表】返回层")
public class SysLogVO extends SysLogDTO {

}