package com.mine.upmsx.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.mine.common.feign.entity.upmsx.SysLog;

/**
 * @description: 【日志表】代理层
 * @author: Generated by jax-li
 * @create: 2020-08-20
 */
public interface ISysLogService extends IService<SysLog> {

}
