package com.mine.upmsx.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.mine.common.feign.entity.upmsx.SysLog;
import com.mine.upmsx.mapper.SysLogMapper;
import com.mine.upmsx.service.ISysLogService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

/**
 * @description: 【日志表】实现层
 * @author: Generated by jax-li
 * @create: 2020-08-20
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class SysLogServiceImpl extends ServiceImpl<SysLogMapper, SysLog> implements ISysLogService {

}
