package com.mine.upmsx.service.impl;

import cn.hutool.core.bean.BeanUtil;
import cn.hutool.core.collection.CollectionUtil;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.mine.common.feign.entity.SysUserBaseVO;
import com.mine.common.feign.entity.upmsx.SysUserBase;
import com.mine.common.security.util.PasswordEncoderUtil;
import com.mine.common.security.util.SecurityUtils;
import com.mine.upmsx.dto.SysUserBaseDTO;
import com.mine.upmsx.mapper.SysUserBaseMapper;
import com.mine.upmsx.service.*;
import com.mine.upmsx.vo.SysRoleVO;
import com.mine.upmsx.vo.SysUserInfoVO;
import com.mine.upmsx.vo.UserVO;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * @author Generated by Jax-li
 * @version v1.0
 * @date 2020-08-12
 * @deprecated 【登录信息表】实现层
 */
@Service
@RequiredArgsConstructor
public class SysUserBaseServiceImpl extends ServiceImpl<SysUserBaseMapper, SysUserBase> implements ISysUserBaseService {

    private final ISysUserClientService sysUserClientService;
    private final ISysUserInfoService sysUserInfoService;
    private final ISysUserRoleService sysUserRoleService;
    private final ISysRoleService sysRoleService;

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void sign(SysUserBaseDTO dto) {
        String clientId = SecurityUtils.getClientId();
        // 主表user_base保存信息
        final Long userId = this.insert(dto);
        // user_client表
        sysUserClientService.add(userId, clientId);
        // user_info
        sysUserInfoService.add(userId);
        // user_role
        sysUserRoleService.add(userId);
    }

    public Long insert(SysUserBaseDTO dto) {
        SysUserBase sysUserBase = BeanUtil.copyProperties(dto, SysUserBase.class);
        sysUserBase.setPassword(PasswordEncoderUtil.encode(sysUserBase.getPassword()));
        baseMapper.insert(sysUserBase);
        return sysUserBase.getId();
    }

    @Override
    public SysUserBase getLoginInfo(String clientId, String userName) {
        SysUserBase userBase = baseMapper.getLoginInfo(clientId, userName);
        if (userBase != null) {
            userBase.setRoles(sysRoleService.getRoleCodesByUserId(userBase.getId()));
        }
        return userBase;
    }

    @Override
    public void updateLastLoginTime(Long userId, LocalDateTime now) {
        baseMapper.updateLastLoginTime(userId, now);
    }

    @Override
    public UserVO info() {
        Long userId = SecurityUtils.getUserId();
        SysUserBaseVO base = BeanUtil.toBean(this.getById(userId), SysUserBaseVO.class);
        SysUserInfoVO info = sysUserInfoService.getByUserId(userId);
        List<SysRoleVO> roles = sysRoleService.getByUserId(userId);

        UserVO vo = new UserVO();
        vo.setBase(base);
        vo.setInfo(info);
        vo.setRoles(roles);
        return vo;
    }
}
