package com.mine.upmsx.controller.web;

import com.mine.common.core.result.Result;
import com.mine.common.log.annotation.SysLog;
import com.mine.upmsx.annotation.SysSign;
import com.mine.upmsx.dto.SysUserBaseDTO;
import com.mine.upmsx.service.ISysUserBaseService;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;

/**
 * 【登录信息表】控制层
 *
 * @author Generated by Jax-li
 * @date 2020-08-12
 */
@Api(tags = {"【登录信息表】模块API"})
@RestController
@RequestMapping("/sysUserBase")
@RequiredArgsConstructor
public class SysUserBaseController {

    private final ISysUserBaseService iSysUserBaseService;

    @SysLog("用户注册")
    @SysSign
    @ApiOperation(value = "用户注册", notes = "登录信息表API")
    @PostMapping
    public Result<?> sign(@RequestBody SysUserBaseDTO dto) {
        iSysUserBaseService.sign(dto);
        return Result.ok();
    }


    @ApiOperation(value = "登录信息表列表查询", notes = "登录信息表API")
    @GetMapping("/list")
    public Result<?> getList(SysUserBaseDTO dto) {
        return Result.ok(iSysUserBaseService.list(dto));
    }

    @SysLog("修改用户信息")
    @ApiOperation(value = "登录信息表更新", notes = "登录信息表API")
    @PutMapping
    public Result<?> update(@RequestBody SysUserBaseDTO dto) {
        iSysUserBaseService.update(dto);
        return Result.ok();
    }

    @ApiOperation(value = "登录信息表删除", notes = "登录信息表API")
    @DeleteMapping("/{id}")
    public Result<?> delete(@PathVariable("id") Long id) {
        iSysUserBaseService.delete(id);
        return Result.ok();
    }

}

