package com.mine.upmsx.controller.web;

import com.mine.common.core.util.R;
import com.mine.common.core.util.WebUtils;
import com.mine.upmsx.dto.SysLogDTO;
import com.mine.upmsx.service.ISysLogService;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;


/**
 * @description: 【日志表】控制层
 * @author: Generated by jax-li
 * @create: 2020-08-20
 */
@Slf4j
@Api(tags = {"【日志表】模块API"})
@RestController
@RequiredArgsConstructor
@RequestMapping("/sysLog")
public class SysLogController {

    private final ISysLogService iSysLogService;

    @ApiOperation(value = "日志表列表查询")
    @GetMapping
    public R list(SysLogDTO dto) {
        return R.ok(iSysLogService.list(dto));
    }

    @ApiOperation(value = "日志表详细查询")
    @GetMapping("/{id}")
    public R detail(@PathVariable("id") Long Id) {
        return R.ok(iSysLogService.detail(Id));
    }

    @ApiOperation(value = "日志表添加")
    @PostMapping
    public R insert(@RequestBody SysLogDTO dto) {
        HttpServletRequest request = WebUtils.getRequest();
        iSysLogService.insert(dto);
        return R.ok();
    }

    @ApiOperation(value = "日志表更新")
    @PutMapping
    public R update(@RequestBody SysLogDTO dto) {
        iSysLogService.update(dto);
        return R.ok();
    }

    @ApiOperation(value = "日志表删除")
    @DeleteMapping("/{id}")
    public R delete(@PathVariable("id") Long id) {
        iSysLogService.delete(id);
        return R.ok();
    }
}

