package com.mine.upmsx.controller.web;

import com.mine.common.core.util.R;
import com.mine.common.log.annotation.SysLog;
import com.mine.common.security.util.SecurityUtils;
import com.mine.upmsx.dto.SysUserBaseDTO;
import com.mine.upmsx.service.ISysUserBaseService;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.web.bind.annotation.*;

/**
 * @description: 【登录信息表】控制层
 * @author: Generated by Jax-li
 * @create: 2020-08-12
 * @version: v1.0
 */
@Slf4j
@Api(tags = {"【登录信息表】模块API"})
@RestController
@RequestMapping("/sysUserBase")
@RequiredArgsConstructor
public class SysUserBaseController {

    private final ISysUserBaseService iSysUserBaseService;

    @ApiOperation(value = "登录信息表列表查询", notes = "登录信息表API")
    @GetMapping("/list")
    public R getList(SysUserBaseDTO dto) {
        return R.ok(iSysUserBaseService.list(dto));
    }

    @ApiOperation(value = "登录信息表详细查询", notes = "登录信息表API")
    @GetMapping("/{id}")
    public R detail(@PathVariable("id") Long id) {
        return R.ok(iSysUserBaseService.detail(id));
    }

    @SysLog("新增用户")
    @ApiOperation(value = "登录信息表添加", notes = "登录信息表API")
    @PostMapping
    public R insert(@RequestBody SysUserBaseDTO dto) {
        iSysUserBaseService.insert(dto);
        return R.ok();
    }

    @ApiOperation(value = "登录信息表更新", notes = "登录信息表API")
    @PutMapping
    public R update(@RequestBody SysUserBaseDTO dto) {
        iSysUserBaseService.update(dto);
        return R.ok();
    }

    @ApiOperation(value = "登录信息表删除", notes = "登录信息表API")
    @DeleteMapping("/{id}")
    public R delete(@PathVariable("id") Long id) {
        iSysUserBaseService.delete(id);
        return R.ok();
    }

}

